### PR TITLE
Feature {12}

### PR DESCRIPTION
**Pull request by gwiedeman**
## Type of Contribution

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New component
- [ ] Refactoring (no functional changes)
- [ ] Documentation-only

## What does this implement/fix? Explain your changes.

Adds mailbag-specific command line args

## Link to issue?

#12 

- [x] Issue closed
- [ ] Remain open

## Pull Request Checklist

Please check if your PR fulfills the following requirements:
- [x] Make sure you are requesting to the develop branch. Don't PR to main!
- [x] This contribution has sufficient documentation
- [ ] Tests for the changes have been added
- [ ] All tests pass

#### How has this been tested?
**Operating System:** Win10
**Python Version:** 3.9.4

## Licensing
- [X] I agree that the Mailbag Project and the University at Albany, SUNY can release this code under the [MIT license](https://github.com/UAlbanyArchives/mailbag/blob/main/LICENSE).

### CODE REVIEW

**Comment by gwiedeman** [comment]
@baibhavr and @haritgarg this adds the new mailbag args with the minimally functional workflow so you should both take a look and approve.

commands such as this should now work: ```mailbagit path/to/data.mbox -i mbox -d pdf warc```

Of note, the [mbox ](https://github.com/UAlbanyArchives/mailbag/blob/feature-%7B12%7D/mailbag/formats/mbox.py#L16)and [msg ](https://github.com/UAlbanyArchives/mailbag/blob/feature-%7B12%7D/mailbag/formats/msg.py#L17)parsers now expect a single `target_account` arg rather than all the args. We'll need more from the args as they get more complex, but I think that should be parsed more thoughtfully in the controller.

Additionally, since the bagit-python directory arg we are using is support to handle multiple directory inputs, for now the [controller now raises an error](https://github.com/UAlbanyArchives/mailbag/blob/feature-{12}/mailbag/controller.py#L16-L23) if there is more than one directory arg. We'll probably have to handle this better down the road, but this seemed like a better stopgap than just `args.directory[0]`.

**Review by baibhavr — APPROVED** [review]
Looks fine to me.

**Review by haritgarg — APPROVED** [review]
Looks good

**Comment by gwiedeman** [comment]
Okay as last to approve, @haritgarg should squash and merge to develop. You can just to this in the webUI if its easier.

**Pull request merged**
