### PR TITLE
Basic implementation of strawman ABC/parser registry, argparse group

### PR DESCRIPTION
**Pull request by pobocks**
## Type of Contribution

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New component
- [ ] Refactoring (no functional changes)
- [ ] Documentation-only

## What does this implement/fix? Explain your changes.

Adds a class MailFormatParser which serves as an abstract base class and a registry for parsers, and a dummy parser as an example.

## Link to issue?

Relates to #19 
...

- [ ] Issue closed
- [x] Remain open

## Pull Request Checklist

Please check if your PR fulfills the following requirements:
- [ ] For new components, make sure you are requesting to a separate branch. Don't PR to main!
- [ ] This contribution has sufficient documentation
- [ ] Tests for the changes have been added
- [ ] All tests pass

#### How has this been tested?
**Operating System:** …
**Python Version:** …

## Licensing
- [x] I agree that the Mailbag Project and the University at Albany, SUNY can release this code under the [MIT license](https://github.com/UAlbanyArchives/mailbag/blob/main/LICENSE).

### CODE REVIEW

**Comment by gwiedeman** [comment]
At least on Windows I'm getting an error after running `setup.py` in a virtualenv. Seems like the parsers directory has to be listed somewhere no?

Script:
```
import mailbag
mailbag.gui()
```

Error:
```
Traceback (most recent call last):
  File "C:\Users\greg\win\mtest1.py", line 1, in <module>
    import mailbag
  File "C:\Users\greg\win\python-virtual-environments\mailbag1\lib\site-packages\mailbag-0.0.1-py3.9.egg\mailbag\__init__.py", line 10, in <module>
    from .parser import EmailFormatParser
  File "C:\Users\greg\win\python-virtual-environments\mailbag1\lib\site-packages\mailbag-0.0.1-py3.9.egg\mailbag\parser.py", line 44, in <module>
    import_parsers()
  File "C:\Users\greg\win\python-virtual-environments\mailbag1\lib\site-packages\mailbag-0.0.1-py3.9.egg\mailbag\parser.py", line 37, in import_parsers
    for filename in listdir(parser_dir):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\greg\\win\\python-virtual-environments\\mailbag1\\lib\\site-packages\\mailbag-0.0.1-py3.9.egg\\mailbag\\parsers'
```

**Comment by baibhavr** [comment]
When I run mailbag>__init__.py, I'm getting the following errors,

`
Traceback (most recent call last):
  File "/home/<username>/git/mailbag/mailbag/__init__.py", line 10, in <module>
    from .parser import EmailFormatParser
ImportError: attempted relative import with no known parent package
`

**Comment by gwiedeman** [comment]
@baibhavr I *think* I fixed the import path issue you ran across. Let me know if it still breaks. The error I found is still happening, but I'm not sure why `setup.py` seems to be ignoring the `parsers` directory.

**Comment by baibhavr** [comment]
> @baibhavr I _think_ I fixed the import path issue you ran across. Let me know if it still breaks. The error I found is still happening, but I'm not sure why `setup.py` seems to be ignoring the `parsers` directory.

@gwiedeman  After git pull on the branch, now I'm getting the following errors,

'
Traceback (most recent call last):
  File "/home/baibhav/git/mailbag/mailbag/__init__.py", line 10, in <module>
    from mailbag.parser import EmailFormatParser
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/baibhav/.local/share/virtualenvs/mailbag-kTZMaqNJ/lib/python3.8/site-packages/baibhav-0.0.1-py3.8.egg/mailbag/__init__.py", line 10, in <module>
    from mailbag.parser import EmailFormatParser
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/baibhav/.local/share/virtualenvs/mailbag-kTZMaqNJ/lib/python3.8/site-packages/baibhav-0.0.1-py3.8.egg/mailbag/parser.py", line 44, in <module>
    import_parsers()
  File "/home/baibhav/.local/share/virtualenvs/mailbag-kTZMaqNJ/lib/python3.8/site-packages/baibhav-0.0.1-py3.8.egg/mailbag/parser.py", line 37, in import_parsers
    for filename in listdir(parser_dir):
NotADirectoryError: [Errno 20] Not a directory: '/home/baibhav/.local/share/virtualenvs/mailbag-kTZMaqNJ/lib/python3.8/site-packages/baibhav-0.0.1-py3.8.egg/mailbag/parsers'

'

**Comment by gwiedeman** [comment]
@baibhavr That one looks like it might be the same issue I was coming across. The new commit may fix it if you run `setup.py` again. Looks like `setuptools.find_packages()` was ignoring the parsers directory because it had no `__init__.py` file, but `setuptools.find_namespace_packages()` seems to work for me. `setup.py` is now copying over `parsers` and everything appears to work for me,

@pobocks when you get a chance, can you double check me on these?

**Comment by haritgarg** [comment]
@gwiedeman I am getting "no command supplied error" while running setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

Can you provide me the exact command ?

**Comment by haritgarg** [comment]
@gwiedeman I tried running "python setup.py test" after pulling the updated repository but I am getting an error that __init__.py file is missing.
Capture

**Comment by pobocks** [comment]
@gwiedeman find_namespace_packages should do it - the other way to handle it would be to make it a package or to manually specify it, but I think this is the right way to go.

@baibhavr in addition to the fix that Greg did, if you want to run the script, you don't want to run `mailbag/__init__.py` directly - what you want to do is to install the package (`pip install -e .` from the top directory should install it in editable mode, so that changes to the package are reflected in the installed package), and then run one of the stubs created [here](https://github.com/UAlbanyArchives/mailbag/blob/0a084e8d64d5364ad44c429859d8c29ced27346a/setup.py#L22)

@haritgarg The only functionality setup.py has at the moment is constructing the package - to do that, you'd run `setup.py sdist`  Testing is via pytest.

**Review by haritgarg — APPROVED** [review]
The configurations works fine locally on my machine.
Approving the merge from my side.

**Comment by baibhavr** [comment]
It worked for me after recommended steps/changes.

**Review by baibhavr — APPROVED** [review]
Worked fine for me with changes and recommended steps.

**Comment by gwiedeman** [comment]
This was already merged so I think it can be closed?

**Pull request closed without merging**
